Resources:
  AnimalsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Animals
      AttributeDefinitions:
        - AttributeName: AnimalId
          AttributeType: S
        - AttributeName: Location
          AttributeType: S
        - AttributeName: SubLocation
          AttributeType: S
      KeySchema:
        - AttributeName: AnimalId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 100
        WriteCapacityUnits: 50
      GlobalSecondaryIndexes:
        - IndexName: LocationAnimalIndex
          KeySchema:
            - AttributeName: Location
              KeyType: HASH
            - AttributeName: SubLocation
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 1
